# Generated by Django 5.2 on 2025-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(null=True)),
                ('content', models.CharField(null=True)),
                ('slides', models.JSONField(null=True)),
            ],
        ),
    ]
