# Generated by Django 5.2 on 2025-08-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidegenerationrequest',
            name='color',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='slidegenerationrequest',
            name='font',
            field=models.CharField(null=True),
        ),
    ]
