# Generated by Django 5.2 on 2025-08-15 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slidegenerationrequest_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidegenerationrequest',
            name='max_slides',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='slidegenerationrequest',
            name='min_slides',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='slidegenerationrequest',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slidegenerationrequest',
            name='content',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slidegenerationrequest',
            name='font',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slidegenerationrequest',
            name='topic',
            field=models.CharField(blank=True, null=True),
        ),
    ]
